INSERT INTO VSUC_EMPRESAS_TLCC
(BDCODEMP, BDCHAVE, BDCODCENTRO, BDCODTPCC, BDDEBCRE, BDVALOR)
VALUES (
:enterpriseCode, --EMPRESA
:key , --CHAVE
:centerCostPlan, -- PLANO CENTRO DE CUSTO
:centerCost, --PLANO DE CUSTO
:valueType, -- DEBITO(0) E CREDITO(1)
:value -- VALOR
)