SELECT 
C.BDCODEMP, ----0
C.BDCHAVE,------1
C.BDCODCENTRO,--2
C.BDCODTPCC,----3
C.BDDEBCRE,-----4
C.BDVALOR,------5
L.BDCREDITO,----6
L.BDDEBITO------7
FROM VSUC_EMPRESAS_TLCC C
INNER JOIN VSUC_EMPRESAS_TLAN L
ON L.BDCODEMP = C.BDCODEMP AND L.BDCHAVE = C.BDCHAVE
WHERE C.BDCODEMP = :enterpriseCode AND L.BDREFERENCIA = :reference and L.BDTIPOLANORIG  = 100