SELECT 
C.BDCODEMP,
C.BDCHAVE,
C.BDCODCENTRO,
C.BDCODTPCC,
C.BDDEBCRE,
C.BDVALOR,
L.BDCREDITO,
L.BDDEBITO
FROM VSUC_EMPRESAS_TLCC C
INNER JOIN VSUC_EMPRESAS_TLAN L
ON L.BDCODEMP = C.BDCODEMP AND L.BDCHAVE = C.BDCHAVE
WHERE C.BDCODEMP = :enterpriseCode AND L.BDREFERENCIA = :reference and L.BDTIPOLANORIG  = 100